<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fo="http://www.w3.org/1999/XSL/Format">
	<xsl:output method="xml" indent="yes"/>
	<xsl:template match="/">
		<fo:root>
			<fo:layout-master-set>
				<fo:simple-page-master master-name="A4-portrait" page-height="29.7cm" page-width="21.0cm" margin="2cm">
					<fo:region-body/>
				</fo:simple-page-master>
			</fo:layout-master-set>
			<fo:page-sequence master-reference="A4-portrait">
				<fo:flow flow-name="xsl-region-body">
					<fo:block font-family="Helvetica">
						<xsl:apply-templates select="/flights/item"/>
					</fo:block>
				</fo:flow>
			</fo:page-sequence>
		</fo:root>
	</xsl:template>
	<xsl:template match="item">
		<fo:external-graphic content-width="140mm" content-height="120mm" padding-left="50mm" padding-top="-20mm" src="header.png"/>
		<fo:block font-size="24pt" font-weight="bold" margin-bottom="1mm">Flight</fo:block>
		<fo:block-container background-color="#f7d4d4" height="50mm">
			<fo:block-container width="70mm" left="10mm" top="10mm" position="absolute">
				<fo:block>
					<fo:block font-size="20pt" margin-bottom="1mm">From</fo:block>&#x2028;
					<xsl:apply-templates select="origin"/>
				</fo:block>
			</fo:block-container>
			<fo:block>
				<fo:block margin-top="20mm" margin-left="55mm">Duration&#x2028;<xsl:value-of select="durationFormatted"/>
				</fo:block>
				<fo:external-graphic content-width="14mm" content-height="14mm" padding-left="55mm" src="arrow.png"/>
			</fo:block>
			<fo:block-container width="70mm" left="90mm" top="10mm" position="absolute">
				<fo:block>
					<fo:block font-size="20pt" margin-bottom="1mm">To</fo:block>&#x2028;
					<xsl:apply-templates select="destination"/>
				</fo:block>
			</fo:block-container>
		</fo:block-container>
		<fo:block font-size="20pt" font-weight="bold" margin-top="10mm">Takeoff</fo:block>
		<fo:block-container background-color="#f7d4d4" height="30mm" margin-top="1mm">
			<fo:block margin-top="5mm" margin-left="5mm"><xsl:apply-templates select="takeoffTime"/></fo:block>
		</fo:block-container>
		<fo:block font-size="20pt" font-weight="bold" margin-top="10mm">Other info</fo:block>
		<fo:block-container background-color="#f7d4d4" height="30mm">
			<fo:block-container width="70mm" left="10mm" top="5mm" position="absolute">
				<fo:block>
					<fo:block font-weight="bold" font-size="20pt">Plane</fo:block>&#x2028;
					<xsl:apply-templates select="plane"/>
				</fo:block>
			</fo:block-container>
			<fo:block-container width="70mm" left="90mm" top="5mm" position="absolute">
				<fo:block>
					<fo:block font-weight="bold" font-size="20pt">Company</fo:block>&#x2028;
					<xsl:apply-templates select="airline"/>
				</fo:block>
			</fo:block-container>
		</fo:block-container>
		<fo:block right="10mm" position="relative" text-align="right" font-weight="bold" font-size="26pt" margin-top="20mm">Price: <xsl:value-of select="price"/>€</fo:block>
		<fo:block color="#afafaf" margin-top="10mm">This page has been generated by planeApp software. © 2019 </fo:block>
		<fo:block page-break-before="auto"/>
	</xsl:template>
	<xsl:template match="origin|destination">
		<fo:block font-weight="bold" font-size="18pt">
			<xsl:value-of select="name"/>&#x2028;</fo:block>
		<xsl:value-of select="country"/>&#x2028;
		(<xsl:value-of select="lat"/>,
		<xsl:value-of select="lon"/>)
	</xsl:template>
	<xsl:template match="takeoffTime">
		<fo:block font-weight="bold">Date:</fo:block><xsl:value-of select="dayOfWeek"/> - <xsl:value-of select="dayOfMonth"/>.<xsl:value-of select="monthValue"/>.<xsl:value-of select="dayOfYear"/>&#x2028;
		<fo:block margin-top="1mm" font-weight="bold">Time:</fo:block><xsl:value-of select="hour"/>:<xsl:value-of select="minute"/>
	</xsl:template>
	<xsl:template match="plane">
		<xsl:value-of select="name"/>, 
		<xsl:value-of select="seats"/> seats
	</xsl:template>
	<xsl:template match="airline">
		<xsl:value-of select="name"/>, 
		<xsl:value-of select="originCountry"/>
	</xsl:template>
</xsl:stylesheet>
